name: Download and Update File

on:
  schedule:
    - cron: '0 0 * * *' # Run once a day at midnight UTC
    
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      #with:
      #  ref: ${{ github.head_ref }}

    #- name: Download file
    #  run: |
    #    curl -o downloaded_file.txt https://kirilla.se/misc/random

    - name: Debug
      run: |
        pwd
        ls -la

    - name: Dig
      run: |
        #dig @zonedata.iis.se se AXFR > se.zone.txt
        dig @zonedata.iis.se nu AXFR > nu.zone.txt

    - name: Post-dig
      run: |
        find . 2>/dev/null

    - name: Prune
      run: |
        chmod +x ./clean-zone.sh
        #./clean-zone.sh < se.zone.txt > se.zone.clean.txt
        ./clean-zone.sh < nu.zone.txt > nu.zone.clean.txt

    - name: Post-prune
      run: |
        find . 2>/dev/null

    - name: Git status
      id: check_changes
      run: |
        git_status=$(git status --porcelain)
        if [ -z "$git_status" ]; then
          echo "No changes to commit."
          echo "::set-output name=changes::false"
        else
          echo "There are changes to commit."
          echo "::set-output name=changes::true"
        fi

    - name: Git commit and push
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name "kirilla"
        git config --global user.email "jonas@kirilla.se"
        #git add se.zone.clean.txt
        git add nu.zone.clean.txt
        git commit -m "Update downloaded file"
        git push
