name: Download and Update File

on:
  schedule:
    - cron: '0 0 * * *' # Run once a day at midnight UTC
    
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      #with:
      #  ref: ${{ github.head_ref }}

    - name: Download file
      run: |
        curl -o downloaded_file.txt https://kirilla.se/misc/random

    - name: Debug
      run: |
        pwd
        ls -la

    - name: Commit and push changes
      run: |
        git config --global user.name "kirilla"
        git config --global user.email "jonas@kirilla.se"
        git add downloaded_file.txt
        git commit -m "Update downloaded file"
        git push
